---
title: "Recreation Unlimited Dashboard"
output:
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r, echo = FALSE, warning = FALSE, message = FALSE}
# app.R (single-file Shiny App)

# Access the necessary packages
library(shiny) 
library(shinydashboard)
library(plotly)
library(lessR)
library(plyr)

# User Interface Script

header <- dashboardHeader(title = "Recreation Unlimited Dashboard",
                          dropdownMenuOutput("msgOutput"),
                          dropdownMenuOutput("notsOutput"))

sidebar <- dashboardSidebar(
  sidebarMenuOutput("menu"),
  textOutput("res"))

body <- dashboardBody(
  tabItems(
    tabItem(tabName = "Home",
            h2("Employee Demographics Overview"),
            fluidRow(
              column(width = 10,
                     box("Employee Age Distribution", width = 6,
                         plotlyOutput("ageHist", height = 400,
                                      width = 500)),
                     valueBoxOutput("ageBox"),
                     box("Employee Sex Composition", width = 4,
                         plotlyOutput("employeeSPie", height = 250, 
                                      width = 300)))),
            fluidRow(
              column(width = 10,
                     tabBox(id = "PieBox", width = 10, side = "left", 
                            tabPanel(title = "Employee Race and Ethnicity Composition",
                                     fluidRow(
                                     column(width = 5,
                                            h4("Employee Race Composition"),
                                            plotlyOutput("racePie", height = 300,
                                                        width = 400)),
                                     column(width = 4,
                                            h4("Employee Ethnicity Composition"),
                                            plotlyOutput("ethPie", height = 300,
                                                         width = 400)))),
                            tabPanel(title = "Employee Disability and Veteran Statuses",
                                     fluidRow(
                                       column(width = 4, 
                                              h4("Employee Disability Status"),
                                              plotlyOutput("disPie", height = 300,
                                                           width = 500)),
                                       column(width = 4,
                                              h4("Employee Veteran Status"),
                                              plotlyOutput("vetPie", height = 300,
                                                           width = 400)))))))),
    tabItem(tabName = "Survey",
            h2("Empolyee Survey Results"),
            fluidRow(
              column(width = 8,
                     valueBoxOutput("JSavg"),
                     valueBoxOutput("ENGavg"),
                     valueBoxOutput("TIavg"))),
            fluidRow(
              column(width = 10,
                tabBox(id = "Survey Scale Plots",
                       selected = "Job Satisfaction",
                       width = 10, side = "left",
                       tabPanel(title = "Job Satisfaction",
                                plotlyOutput("JSPlot",
                                             height = 300,
                                             width = 800)),
                       tabPanel(title = "Engagement",
                               plotlyOutput("ENGPlot", height = 300, 
                                            width = 800)),
                       tabPanel(title = "Turnover Intentions", 
                              plotlyOutput("TIPlot", height = 300, 
                                           width = 800))))),
            fluidRow(
              column(width = 10,
                valueBoxOutput("surveyBox", width = 10)))),
      tabItem(tabName = "PM",
              h2("Performance Management"),
              fluidRow(
                h3("Employee Sales and BARS Performance"),
                tabBox(id = "PM Indicators",
                       width = 8, side = "left",
                       tabPanel(title = "Sales Performance",
                                fluidRow( 
                                  plotlyOutput("salesHist", height = 300,
                                               width = 700),
                                  uiOutput("salesBox"))),
                       tabPanel(title = "BARS Rating",
                                fluidRow(
                                  plotlyOutput("barsHist", height = 300,
                                               width = 700),
                                  uiOutput("barsBox"))))),
              fluidRow(
                h3("Sales and Survey Results"),
                tabBox(id = "ScatterPlots",
                       width = 8, side = "left",
                  tabPanel(title = "Sales and Job Satisfaction",
                           plotlyOutput("JSScatter", 
                                        height = 300, 
                                        width = 600)),
                  tabPanel(title = "Sales and Engagement", 
                           plotlyOutput("ENGScatter",
                                        height = 300,
                                        width = 600)),
                  tabPanel(title = "Sales and Turnover Intentions",
                           plotlyOutput("TIScatter",
                                        height = 300,
                                        width = 600))))),
      
      tabItem(tabName = "Training",
              h2("Training Results"),
              fluidRow(
                uiOutput("tBox")),
              fluidRow(
                column(width = 10,
                       box(h3("Training Results"), 
                           width = 8,
                           plotlyOutput("Tplot", 
                                        height = 300,
                                        width = 600)))),
              fluidRow(
                box(paste0("Retain Old training program due to higher pre- vs. post-test results"),
                           title = "Results Overview",
                           width = 6,
                           status = "warning",
                           solidHeader = TRUE,
                           background = NULL, 
                           collapsible = TRUE, collapsed = FALSE)))))

# Server Script

server <- function(input, output, session) {
  
  # Read in csv Files
  surveydata <- read.csv("SurveyData.csv")
  pmdata <- read.csv("PerformanceData.csv")
  persdata <- read.csv("PersonalData.csv")
  
  # Merge surveydata and pmdata
  mergeddata <- merge(surveydata, pmdata, by = c("EmployeeID"), all.x = TRUE)

# dashboardHeader Outputs
  
output$msgOutput <- renderMenu({
  msgs <- apply(read.csv("MessageData.csv"), 1, function(row) {
    messageItem(from = row[["From"]], message = row[["Message"]])})
  dropdownMenu(type = "messages", .list = msgs)})
  
output$notsOutput <- renderMenu({
  nots <- apply(read.csv("NotificationData.csv"), 1, function(row) {
    notificationItem(text = row[["Message"]])})
  dropdownMenu(type = "notifications", .list = nots)})


# dashboardSidebar Outputs

output$menu <- renderMenu({
  sidebarMenu(id = "tabs",
              menuItem("Home",
                       tabName = 'Home',
                       icon = icon('home')),
              menuItem("Survey",
                       tabName = 'Survey',
                       icon = icon('list-ul')),
              menuItem("Performance Management",
                       tabName = 'PM',
                       icon = icon('star')),
              menuItem("Training",
                       tabName = 'Training',
                       icon = icon('cogs')))})

output$res <- renderText({
  paste0("Current Tab: ", input$tabs)})

# dashboardBody Outputs (by Tab)

## Home Tab

output$ageHist <- renderPlotly({
  
  # Create x and y axis titles
  x <- list(title = "Age")
  y <- list(title = "Number of Employees")
  
  # Create Histogram displaying employee Age
  plot_ly(data = persdata, x = ~Age, type = "histogram") %>%
    layout(xaxis = x, yaxis = y)})
  
output$ageBox <- renderValueBox({
  
  # Filter persdata for employees over the age of 35.0
  persfilter <- subset(persdata, Age>="35.0")
  
  # Count the number of employees over the age of 35.0 
  count(persfilter, vars = "EmployeeID") # Number of employees over 35.0: 195
  
  # Count the number of total employees
  count(persdata, vars = "EmployeeID") # Number of total employees: 521
  
  # Compute the percentage of employees over the age of 35.0
  195/521
  
  # Create the value box with the computed value (rounded to one decimal place)
  valueBox(paste0("37.4%"), "Employees over 35", icon = icon("percent"),  
           color = "blue")})

output$racePie <- renderPlotly({
  
  # Create Pie chart based on employee Race
  plot_ly(data = persdata, labels = ~Race, values = ~EmployeeID, type = "pie") %>%
    
  # Position the legend inside the plot
    layout(legend = list(x = -0.1, y = -0.9))})

output$ethPie <- renderPlotly({
  
  # Create Pie chart based on employee Ethnicity
  plot_ly(data = persdata, labels = ~Ethnicity, values = ~EmployeeID, type = "pie") %>%
  
  # Position the legend inside the plot 
    layout(legend = list(x = 1, y = -0.9))})
  

output$disPie <- renderPlotly({
  
  # Create Pie chart based on employee Disability status
  plot_ly(data = persdata, labels = ~Disability, values = ~EmployeeID, type = "pie") %>%
    
  # Position the legend inside the plot
    layout(legend = list(x = -0.1, y = -0.9))})

output$vetPie <- renderPlotly({
  
  # Create Pie chart based on employee Veteran status
  plot_ly(data = persdata, labels = ~Veteran, values = ~EmployeeID, type = "pie") %>%
    
  # Position the legend inside the plot 
    layout(legend = list(x = 1, y = -0.9))})

output$employeeSPie <- renderPlotly({
  
  # Create pie chart based on employee Sex
  plot_ly(data = persdata, labels = ~Sex, values = ~EmployeeID, type = "pie") %>%
    
    # Position the legend
    layout(legend = list(x = -0.1, y = -0.9))})

## Survey Tab

output$surveyBox <- renderValueBox({
  
  valueBox(paste0("96.4%"), "Employee Survey Participation", icon = icon("check-square"),  
           color = "green")})
  
output$JSPlot <- renderPlotly({
  
  # Create x and y axis titles
  x <- list(title = "Job Satisfaction")
  y <- list(title = "Response Frequency")
    
    # Create JS Scale Score
    mergeddata$JS_Scale <- rowMeans(mergeddata[,c("JobSat1", "JobSat2", 
                                                  "JobSat3")], na.rm = TRUE)
    
    # Create JSPlot
    plot_ly(data = mergeddata, x = ~JS_Scale, type = "histogram") %>%
    layout(xaxis = x, yaxis = y)})
  
output$ENGPlot <- renderPlotly({
  
  # Create x and y axis titles
  x <- list(title = "Engagement")
  y <- list(title = "Response Frequency")
    
  # Create ENG Scale Score
  mergeddata$ENG_Scale <- rowMeans(mergeddata[,c("Engage2", "Engage3")], 
                                     na.rm = TRUE)
    
  # Create ENGPlot
  plot_ly(data = mergeddata, x = ~ENG_Scale, type = "histogram") %>%
    layout(xaxis = x, yaxis = y)})
  
output$TIPlot <- renderPlotly({
  
  # Create x and y axis titles
  x <- list(title = "Turnover Intentions")
  y <- list(title = "Response Frequency")
    
  # Create TI Scale Score
  mergeddata$TI_Scale <- rowMeans(mergeddata[,c("TurnoverInt1", "TurnoverInt2",
                                                  "TurnoverInt3")], na.rm = TRUE)
    
   # Create TIPlot
  plot_ly(data = mergeddata, x = ~TI_Scale, type = "histogram") %>%
    layout(xaxis = x, yaxis = y)})

output$JSavg <- renderValueBox({
  
  # Create JS variable 'JS' and compute the mean
  JS = mergeddata$JS_Scale
  mean(JS) # 3.25
  
  # Create the value box 
  valueBox(paste0("3.25"), "Average Job Satisfaction", color = "yellow")})

output$ENGavg <- renderValueBox({
  
  # Create ENG variable 'ENG' and compute the mean
  ENG = mergeddata$ENG_Scale
  mean(ENG) #3.03
  
  # Create the value box 
  valueBox(paste0("3.03"), "Average Engagement", color = "teal")})

output$TIavg <- renderValueBox({
  
  # Create TI variable and compute the mean
  TI = mergeddata$TI_Scale
  mean(TI) # 3.14
  
  # Create the value box
  valueBox(paste0("3.14"), "Average Intent to Turnover", color = "red")})

## Performance Management Tab

output$salesHist <- renderPlotly({
  
  # Create x and y axis titles
  x <- list(title = "Sales")
  y <- list(title = "Frequency")
  
  # Create histogram based on employee Sales
  plot_ly(data = mergeddata, x = ~Sales, type = "histogram") %>%
    layout(xaxis = x, yaxis = y)})

output$barsHist <- renderPlotly({
  
  # Create x and y axis titles 
  x <- list(title = "BARS Rating")
  y <- list(title = "Frequency")
  
  # Create histogram based on employee BARS Ratings
  plot_ly(data = mergeddata, x = ~BARSrating, type = "histogram")%>%
    layout(xaxis = x, yaxis = y)})

output$salesBox <- renderUI({
    infoBox(
      "Sales Average $",
      paste0("$72,338"),
      subtitle = "Average employee sales",
      icon = icon("industry"),
      color = "blue",
      width = 8,
      fill = TRUE)})
  
output$barsBox <- renderUI({
    infoBox(
      "BARS Average",
      paste0("3.13"),
      subtitle = "Average employee BARS rating",
      icon = icon("star"),
      color = "blue",
      width = 8,
      fill = TRUE)})

output$JSScatter <- renderPlotly({
  
  # Create x and y axis titles
  x <- list(title = "Job Satisfaction")
  y <- list(title = "Sales")
  
  # Create JS Scale Score
  mergeddata$JS_Scale <- rowMeans(mergeddata[,c("JobSat1", "JobSat2", "JobSat3")], na.rm = TRUE)
  
  # Create Sales-Job Satisfaction Scatter Plot
  plot_ly(data = mergeddata, x = ~JS_Scale, y = ~Sales, type = "scatter") %>%
    layout(xaxis = x, yaxis = y)})

output$ENGScatter <- renderPlotly({
  
  # Create x and y axis titles
  x <- list(title = "Engagement")
  y <- list(title = "Sales")
  
  # Create ENG Scale Score
  mergeddata$ENG_Scale <- rowMeans(mergeddata[,c("Engage2", "Engage3")], na.rm = TRUE)
  
  # Create ENG_Scale-Sales Scatter Plot
  plot_ly(data = mergeddata, x = ~ENG_Scale, y = ~ Sales, type = "scatter") %>%
    layout(xaxis = x, yaxis = y)})

output$TIScatter <- renderPlotly({
  
  # Create x and y axis titles
  x <- list(title = "Turnover Intentions")
  y <- list(title = "Sales")
  
  # Create TI Scale Score
  mergeddata$TI_Scale <- rowMeans(mergeddata[,c("TurnoverInt1", "TurnoverInt2",
                                                  "TurnoverInt3")], na.rm = TRUE)
    
  # Create TI_Scale-Sales Scatter Plot
  plot_ly(data = mergeddata, x = ~TI_Scale, y = ~Sales, type = "scatter") %>%
    layout(xaxis = x, yaxis = y)})


## Training Tab
  
output$Tplot <- renderPlotly({
    
    # Read in Training Data
    tdata <- read.csv("TrainingData.csv")
    
    # Create Difference Variable
    tdata$Difference = tdata$PostTest - tdata$PreTest
    
    means <- tapply(tdata$Difference, tdata$Group, mean)
    
    plot_ly(data = tdata, x = ~Group, y = ~Difference, type = "bar")})

output$tBox <- renderUI({
  infoBox(
      h3("Training Participants"),
      fluidRow(
        paste0("Control Group (Old): 30"),
        paste0("Experimental Group (New): 30")),
      icon = icon("user-circle"),
      color = "olive",
      width = 6,
      fill = TRUE)})

  }

shinyApp(ui = dashboardPage(skin = "blue", header, sidebar, body), 
         server)
```
