---
title: "Shiny Dashboard Old Faithful Example"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include = FALSE}
require("knitr")
opts_knit$set(root.dir = "~/R Files")

install.packages("flexdashboard", repos = "http://cran.us.r-project.org")
library(flexdashboard)

# Access the datasets package.
library(datasets)

# Access the dataset 'faithful.'
data(faithful)
```

Column {.sidebar} 
--------------------------------------------------------

Waiting time between eruptions and the duration of the eruption 
or the Old Faithful geyser in Yellowstone National Park, 
Wyoming, USA. 

```{r}
selectInput(
  "n_breaks", label = "Number of bins:",
  choices = c(10, 20, 35, 50), selected = 20
)

sliderInput(
  "bw_adjust", label = "Bandwith adjustment:",
  min = 0.2, max = 2, value = 1, step = 0.2
)
```

Column {.sidebar}
--------------------------------------------------------

## Geyser Eruption Duration

```{r}
renderPlot({
  erpt = faithful$eruptions
  hist(
    erpt, probability = TRUE, breaks = as.integer(input$n_breaks),
    xlab = "Duration (minutes)", main = "Geyser Eruption Duration",
    col = 'gray', border = 'white'
  )
  
  dens = density(erpt, adjust = input$bw_adjust)
  lines(dens, col = "blue", lwd = 2)
})
```
