---
title: "Shiny Dashboard IV"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r, echo = FALSE, warning = FALSE, message = FALSE}
# app.R (single-file Shiny App)

# Access the necessary packages
library(shiny) 
library(shinydashboard)
library(plotly)
library(lessR)
library(plyr)

# User Interface Script

header <- dashboardHeader(title = "Recreation Unlimited Dashboard",
                          dropdownMenuOutput("msgOutput"),
                          dropdownMenuOutput("notsOutput"))

sidebar <- dashboardSidebar(
  sidebarMenuOutput("menu"),
  textOutput("res"))

body <- dashboardBody(
  tabItems(
    tabItem(tabName = "Home",
            h2("Employee Demographics Overview"),
            fluidRow(
                box("Employee Age Distribution", width = 8,
                    plotlyOutput("ageHist", height = 250, 
                                 width = 400)),
                valueBoxOutput("ageBox")),
            fluidRow(
              box("Employee Race Composition", width = 6,
                    plotlyOutput("racePie", height = 250, 
                                 width = 300)),
              box("Employee Ethnicity Composition", width = 6,
                  plotlyOutput("ethPie", height = 250, 
                               width = 300))),
            fluidRow(
              box("Employee Disability Status", width = 6,
                  plotlyOutput("disPie", height = 250, 
                               width = 300)),
              box("Employee Veteran Status", width = 6,
                  plotlyOutput("vetPie", height = 250,
                               width = 300)))),
    tabItem(tabName = "Survey",
            h2("Survey"),
            fluidRow(
              h3("Employee Engagement Survey Results"),
              tabBox(id = "Survey Scale Plots",
                     selected = "Job Satisfaction",
                     width = 12, side = "right",
                     tabPanel(title = "Job Satisfaction",
                              plotlyOutput("JSPlot", height = 250,
                                           width = 600)),
                     tabPanel(title = "Engagement",
                               plotlyOutput("ENGPlot", height = 250, 
                                            width = 600)),
                     tabPanel(title = "Turnover Intentions", 
                              plotlyOutput("TIPlot", height = 250, 
                                           width = 600))))),
              
      tabItem(tabName = "PM",
              h2("Performance Management"),
              fluidRow(
                h3("Performance Management KPIs"),
                uiOutput("salesBox"),
                uiOutput("barsBox")),
              fluidRow(
                h3("Sales and Survey Results"),
                tabBox(id = "ScatterPlots",
                       width = 12, side = "right",
                  tabPanel(title = "Sales and Job Satisfaction",
                           plotlyOutput("JSScatter", 
                                        height = 250, 
                                        width = 600)),
                  tabPanel(title = "Sales and Engagement", 
                           plotlyOutput("ENGScatter",
                                        height = 250,
                                        width = 600)),
                  tabPanel(title = "Sales and Turnover Intentions",
                           plotlyOutput("TIScatter",
                                        height = 250,
                                        width = 600))))),
      
      tabItem(tabName = "Training",
              h2("Training"),
              fluidRow(
                h3("Training: Old vs New"),
                plotlyOutput("Tplot", height = 250)))))

# Server Script

server <- function(input, output, session) {
  
  # Read in csv Files
  surveydata <- read.csv("SurveyData.csv")
  pmdata <- read.csv("PerformanceData.csv")
  persdata <- read.csv("PersonalData.csv")
  
  # Merge surveydata and pmdata
  mergeddata <- merge(surveydata, pmdata, by = c("EmployeeID"), all.x = TRUE)

# dashboardHeader Outputs
  
output$msgOutput <- renderMenu({
  msgs <- apply(read.csv("MessageData.csv"), 1, function(row) {
    messageItem(from = row[["From"]], message = row[["Message"]])})
  dropdownMenu(type = "messages", .list = msgs)})
  
output$notsOutput <- renderMenu({
  nots <- apply(read.csv("NotificationData.csv"), 1, function(row) {
    notificationItem(text = row[["Message"]])})
  dropdownMenu(type = "notifications", .list = nots)})


# dashboardSidebar Outputs

output$menu <- renderMenu({
  sidebarMenu(id = "tabs",
              menuItem("Home",
                       tabName = 'Home',
                       icon = icon('home')),
              menuItem("Survey",
                       tabName = 'Survey',
                       icon = icon('list-ul')),
              menuItem("Performance Management",
                       tabName = 'PM',
                       icon = icon('star')),
              menuItem("Training",
                       tabName = 'Training',
                       icon = icon('cogs')))})

output$res <- renderText({
  paste0("Current Tab: ", input$tabs)})

# dashboardBody Outputs (by Tab)

## Home Tab

output$ageHist <- renderPlotly({
    
    # Create Histogram displaying employee Age
    plot_ly(data = persdata, x = ~Age, type = "histogram")})
  
output$ageBox <- renderValueBox({
  
  # Filter persdata for employees over the age of 35.0
  persfilter <- subset(persdata, Age>="35.0")
  
  # Count the number of employees over the age of 35.0 
  count(persfilter, vars = "EmployeeID") # Number of employees over 35.0: 195
  
  # Count the number of total employees
  count(persdata, vars = "EmployeeID") # Number of total employees: 521
  
  # Compute the percentage of employees over the age of 35.0
  195/521
  
  # Create the value box with the computed value (rounded to one decimal place)
  valueBox(paste0("37.4%"), "Employees over 35", icon = icon("badge-percent"),  
           color = "blue")})
  
output$racePie <- renderPlotly({
  
  # Create Pie chart based on employee Race
  plot_ly(data = persdata, labels = ~Race, values = ~EmployeeID, type = "pie")})

output$ethPie <- renderPlotly({
  
  # Create Pie chart based on employee Ethnicity
  plot_ly(data = persdata, labels = ~Ethnicity, values = ~EmployeeID, type = "pie")})

output$disPie <- renderPlotly({
  
  # Create Pie chart based on employee Disability status
  plot_ly(data = persdata, labels = ~Disability, values = ~EmployeeID, type = "pie")})

output$vetPie <- renderPlotly({
  
  # Create Pie chart based on employee Veteran status
  plot_ly(data = persdata, labels = ~Disability, values = ~EmployeeID, type = "pie")})

## Survey Tab
  
output$JSPlot <- renderPlotly({
    
    # Create JS Scale Score
    mergeddata$JS_Scale <- rowMeans(mergeddata[,c("JobSat1", "JobSat2", 
                                                  "JobSat3")], na.rm = TRUE)
    
    # Create JSPlot
    plot_ly(data = mergeddata, x = ~JS_Scale, type = "histogram")})
  
output$ENGPlot <- renderPlotly({
    
    # Create ENG Scale Score
    mergeddata$ENG_Scale <- rowMeans(mergeddata[,c("Engage2", "Engage3")], 
                                     na.rm = TRUE)
    
    # Create ENGPlot
    plot_ly(data = mergeddata, x = ~ENG_Scale, type = "histogram")})
  
output$TIPlot <- renderPlotly({
    
    # Create TI Scale Score
    mergeddata$TI_Scale <- rowMeans(mergeddata[,c("TurnoverInt1", "TurnoverInt2",
                                                  "TurnoverInt3")], na.rm = TRUE)
    
    # Create TIPlot
    plot_ly(data = mergeddata, x = ~TI_Scale, type = "histogram")})

## Performance Management Tab
    
output$salesBox <- renderUI({
    infoBox(
      "Sales Average $",
      paste0("$72,338"),
      subtitle = "Average employee sales",
      icon = icon("industry"),
      width = 6,
      fill = TRUE)})
  
output$barsBox <- renderUI({
    infoBox(
      "BARS Average",
      paste0("3.13"),
      subtitle = "Average employee BARS rating",
      icon = icon("star"),
      width = 6,
      fill = TRUE)})

output$JSScatter <- renderPlotly({
    
    # Create JS Scale Score
    mergeddata$JS_Scale <- rowMeans(mergeddata[,c("JobSat1", "JobSat2", "JobSat3")], na.rm = TRUE)
    
    # Create Sales-Job Satisfaction Scatter Plot
    plot_ly(data = mergeddata, x = ~JS_Scale, y = ~Sales, type = "scatter")})

output$ENGScatter <- renderPlotly({
    
    # Create ENG Scale Score
    mergeddata$ENG_Scale <- rowMeans(mergeddata[,c("Engage2", "Engage3")], na.rm = TRUE)
    
    # Create ENG_Scale-Sales Scatter Plot
    plot_ly(data = mergeddata, x = ~ENG_Scale, y = ~ Sales, type = "scatter")})

output$TIScatter <- renderPlotly({
    
    # Create TI Scale Score
    mergeddata$TI_Scale <- rowMeans(mergeddata[,c("TurnoverInt1", "TurnoverInt2",
                                                  "TurnoverInt3")], na.rm = TRUE)
    
    # Create TI_Scale-Sales Scatter Plot
    plot_ly(data = mergeddata, x = ~TI_Scale, y = ~Sales, type = "scatter")})


## Training Tab
  
output$Tplot <- renderPlotly({
    
    # Read in Training Data
    tdata <- read.csv("TrainingData.csv")
    
    # Create Difference Variable
    tdata$Difference = tdata$PostTest - tdata$PreTest
    
    means <- tapply(tdata$Difference, tdata$Group, mean)
    
    plot_ly(data = tdata, x = ~Group, y = ~Difference, type = "bar")})

  }

shinyApp(ui = dashboardPage(skin = "blue", header, sidebar, body), 
         server)
```
