---
title: "Shiny Dashboard I"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r, echo = FALSE, warning = FALSE, message = FALSE}
# app.R (single-file Shiny App)

library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Dashboard",
                  dropdownMenu(type = "messages",
                 messageItem(
                   from = "Sales Department",
                   message = "Sales are steady this month."),
                 messageItem(
                   from = "Support",
                   message = "The new server is ready.",
                   icon = icon("life-ring"),
                   time = "4:01 P.M.")),
    dropdownMenu(type = "notifications",
                 notificationItem(
                   text = "5 new users today",
                   icon("users")),
                 notificationItem(
                   text = "12 itesm delivered",
                   icon("truck"),
                   status = "success")),
    dropdownMenu(type = "tasks", badgeStatus = "success",
                 taskItem(value = 90, color = "green",
                          "Documentation"),
                 taskItem(value = 17, color = "aqua",
                          "Project X"),
                 taskItem(value = 75, color = "yellow",
                          "Server deployment"),
                 taskItem(value = 80, color = "red",
                          "Overall project"))),
                       
  dashboardSidebar(
    sidebarMenu(
      menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
      menuItem("Widgets", icon = icon("th"), tabName = "widgets", badgeLabel = "New",
               badgeColor = "green"))),

   dashboardBody(
    tabItems(
      tabItem(tabName = "dashboard",
              h2("Dashboard"),     
    fluidRow(
      box(width = 8, title = "Histogram", background = "maroon",
          solidHeader = TRUE,
          plotOutput("plot1", height = 250)),
      
      box(width = 4, title = "Controls", status = "info", 
          solidHeader = TRUE, 
          sliderInput("slider", "Observations:", 
                      min = 1, max = 100, value = 50),
          textInput("text", "Text:")))),
    
      tabItem(tabName = "widgets",
              h2("Widgets")))))

server <- function(input, output) {
set.seed(122)
  histdata <- rnorm(500)
  
  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)})  }

shinyApp(ui, server)
```